// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ_TAuPrOqt-UzNyj9Vdy3oa0B6kYqkLs',
    appId: '1:682958128326:web:ddbd937c1a4af7fec703c7',
    messagingSenderId: '682958128326',
    projectId: 'the-wall-a532e',
    authDomain: 'the-wall-a532e.firebaseapp.com',
    storageBucket: 'the-wall-a532e.appspot.com',
    measurementId: 'G-ZWVYV1JYLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl2YG6SDXZHtm79GelUF_ERmOI3RLMZPQ',
    appId: '1:682958128326:android:4357d0f57e59c503c703c7',
    messagingSenderId: '682958128326',
    projectId: 'the-wall-a532e',
    storageBucket: 'the-wall-a532e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZoaXZnT829drfRdoNsmhItPEUofqQHg',
    appId: '1:682958128326:ios:a627ef6fd30e054ac703c7',
    messagingSenderId: '682958128326',
    projectId: 'the-wall-a532e',
    storageBucket: 'the-wall-a532e.appspot.com',
    iosBundleId: 'com.example.theWall',
  );
}
